name: Update README with Activity

on:
  workflow_dispatch:   # 手動觸發
  schedule:
    - cron: "0 * * * *"   # 每小時執行一次

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Workflow 需要修改 README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: 05Ching   # 你的 GitHub 帳號
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}   # 使用你設定的 REPO_TOKEN
