name: Update README with Activity

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
