name: Validate README markers

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check README markers
        run: |
          if ! grep -q "<!--START_SECTION:activity-->" README.md; then
            echo "❌ Missing START_SECTION:activity marker"
            exit 1
          fi
          if ! grep -q "<!--END_SECTION:activity-->" README.md; then
            echo "❌ Missing END_SECTION:activity marker"
            exit 1
          fi
          echo "✅ README markers are present"
